# Shared helpers for ase (sourced, not executed directly)
# shellcheck shell=bash

ASE_SYSTEM_BIN="/usr/local/bin"

ase_die() {
  echo "ase: $*" >&2
  exit 1
}

ase_canonical_path() {
  local path=$1
  if [[ -z $path ]]; then
    return 1
  fi
  if [[ -d $path ]]; then
    (cd "$path" && pwd -P)
  elif [[ -f $path ]]; then
    local dir
    dir=$(cd "$(dirname "$path")" && pwd -P)
    echo "$dir/$(basename "$path")"
  else
    if command -v readlink >/dev/null 2>&1; then
      readlink -f "$path" 2>/dev/null && return 0
    fi
    ase_die "path not found: $path"
  fi
}

ase_write_default_config() {
  local cfg=$1
  local git_root="${ASE_DEFAULT_GIT_ROOT:-}"
  local scripts_dir=""
  if [[ -n $git_root ]] && command -v git >/dev/null 2>&1; then
    git_root=$(git -C "$git_root" rev-parse --show-toplevel 2>/dev/null) || git_root="${ASE_DEFAULT_GIT_ROOT:-}"
  fi
  if [[ -n $git_root && -d "$git_root/script-hub" ]]; then
    scripts_dir="$git_root/script-hub"
  elif [[ -n $git_root ]]; then
    scripts_dir="$git_root"
  fi

  mkdir -p "$(dirname "$cfg")"
  {
    echo '# Generated by ase — edit as needed'
    if [[ -n $scripts_dir ]]; then
      printf 'ASE_SCRIPTS_DIR=%q\n' "$scripts_dir"
      printf 'ASE_GIT_ROOT=%q\n' "$git_root"
    else
      echo 'ASE_SCRIPTS_DIR="$HOME/scripts"'
    fi
    echo 'ASE_GIT_REMOTE="origin"'
    echo 'ASE_GIT_BRANCH="main"'
    if [[ $(id -u) -eq 0 ]]; then
      printf 'ASE_BIN_USER=%q\n' "$ASE_SYSTEM_BIN"
    else
      echo 'ASE_BIN_USER="$HOME/bin"'
    fi
  } >"$cfg"
  echo "ase: wrote default config to $cfg" >&2
}

ase_warn_path_missing() {
  local bin_dir=$1
  [[ -n $bin_dir ]] || return 0
  case ":${PATH}:" in
    *":$bin_dir:"*) return 0 ;;
  esac
  echo "ase: $bin_dir is not on PATH; the command may not run until you add it or use -a." >&2
  echo "ase:  export PATH=\"$bin_dir:\$PATH\"" >&2
  echo "ase:  or: ase install <name> -a  # -> $ASE_SYSTEM_BIN" >&2
}

ase_load_config() {
  local cfg="${ASE_CONFIG:-$HOME/.config/ase/config}"
  if [[ ! -f $cfg ]]; then
    ase_write_default_config "$cfg"
  fi
  if [[ -f $cfg ]]; then
    # shellcheck disable=SC1090
    source "$cfg"
  fi

  if [[ -z ${ASE_SCRIPTS_DIR:-} ]]; then
    ase_die "ASE_SCRIPTS_DIR is not set (env or $cfg)"
  fi

  ASE_GIT_REMOTE="${ASE_GIT_REMOTE:-origin}"
  ASE_GIT_BRANCH="${ASE_GIT_BRANCH:-main}"
  ASE_BIN_USER="${ASE_BIN_USER:-$HOME/bin}"

  if [[ -z ${ASE_GIT_ROOT:-} ]]; then
    if ! command -v git >/dev/null 2>&1; then
      ase_die "git not found; set ASE_GIT_ROOT explicitly"
    fi
    ASE_GIT_ROOT=$(git -C "$ASE_SCRIPTS_DIR" rev-parse --show-toplevel 2>/dev/null) || \
      ase_die "ASE_SCRIPTS_DIR is not inside a git repo; set ASE_GIT_ROOT"
  fi

  ASE_SCRIPTS_DIR=$(ase_canonical_path "$ASE_SCRIPTS_DIR")
  ASE_GIT_ROOT=$(ase_canonical_path "$ASE_GIT_ROOT")

  local prefix="$ASE_GIT_ROOT/"
  if [[ $ASE_SCRIPTS_DIR != "$ASE_GIT_ROOT" && $ASE_SCRIPTS_DIR != "$prefix"* ]]; then
    ase_die "ASE_SCRIPTS_DIR must be inside ASE_GIT_ROOT"
  fi

  if [[ $ASE_SCRIPTS_DIR == "$ASE_GIT_ROOT" ]]; then
    ASE_SCRIPTS_REL=""
  else
    ASE_SCRIPTS_REL="${ASE_SCRIPTS_DIR#"$prefix"}"
  fi
}

ase_require_scripts_dir() {
  ase_load_config
  if [[ ! -d $ASE_SCRIPTS_DIR ]]; then
    ase_die "scripts directory does not exist: $ASE_SCRIPTS_DIR"
  fi
}

# stdout: one script basename per line
ase_enumerate_scripts() {
  ase_require_scripts_dir
  find "$ASE_SCRIPTS_DIR" -maxdepth 1 -type f ! -name '.*' -printf '%f\n' 2>/dev/null | sort ||
    find "$ASE_SCRIPTS_DIR" -maxdepth 1 -type f ! -name '.*' -exec basename {} \; | sort
}

ase_resolve_script_path() {
  local name=$1
  ase_require_scripts_dir
  if [[ -z $name || $name == *"/"* || $name == *".."* ]]; then
    ase_die "invalid script name: ${name:-<empty>}"
  fi
  local path="$ASE_SCRIPTS_DIR/$name"
  if [[ ! -f $path ]]; then
    echo "ase: script not found: $name" >&2
    return 2
  fi
  echo "$path"
}

ase_maybe_chmod_executable() {
  local file=$1
  if [[ -f $file ]] && head -c 2 "$file" 2>/dev/null | grep -q '^#!'; then
    chmod +x "$file" 2>/dev/null || true
  fi
}

ase_git_remote_ref() {
  echo "${ASE_GIT_REMOTE}/${ASE_GIT_BRANCH}"
}

ase_git_path_in_repo() {
  local basename=$1
  if [[ -n $ASE_SCRIPTS_REL ]]; then
    echo "${ASE_SCRIPTS_REL}/${basename}"
  else
    echo "$basename"
  fi
}

ase_unlink_if_points_to() {
  local link_path=$1
  local target=$2
  [[ -e $link_path || -L $link_path ]] || return 0
  [[ -L $link_path ]] || return 0
  local dest
  dest=$(readlink "$link_path" 2>/dev/null) || return 0
  if [[ "$dest" == "$target" ]]; then
    rm -f "$link_path"
    return 0
  fi
  local abs_dest
  if [[ $dest == /* ]]; then
    abs_dest=$(ase_canonical_path "$dest" 2>/dev/null) || abs_dest=$dest
  else
    abs_dest=$(ase_canonical_path "$(dirname "$link_path")/$dest" 2>/dev/null) || return 0
  fi
  if [[ $abs_dest == "$target" ]]; then
    rm -f "$link_path"
  fi
}
