# Shared helpers for ase (sourced, not executed directly)
# shellcheck shell=bash

ASE_SYSTEM_BIN="/usr/local/bin"
ASE_SCRIPT_HUB_LIST_REL="data/script-hub.list"
ASE_INSTALL_LIST_REL="data/install.list"

ase_die() {
  echo "ase: $*" >&2
  exit 1
}

# Drop bash's cached path for a command name (no-op outside bash).
ase_forget_cmd_hash() {
  local name=$1
  [[ -n $name && -n ${BASH_VERSION:-} ]] || return 0
  hash -d "$name" 2>/dev/null || true
}

ase_canonical_path() {
  local path=$1
  if [[ -z $path ]]; then
    return 1
  fi
  if [[ -d $path ]]; then
    (cd "$path" && pwd -P)
  elif [[ -f $path ]]; then
    local dir
    dir=$(cd "$(dirname "$path")" && pwd -P)
    echo "$dir/$(basename "$path")"
  else
    if command -v readlink >/dev/null 2>&1; then
      readlink -f "$path" 2>/dev/null && return 0
    fi
    ase_die "path not found: $path"
  fi
}

ase_write_default_config() {
  local cfg=$1
  local git_root="${ASE_DEFAULT_GIT_ROOT:-}"
  local scripts_dir=""
  if [[ -n $git_root ]] && command -v git >/dev/null 2>&1; then
    git_root=$(git -C "$git_root" rev-parse --show-toplevel 2>/dev/null) || git_root="${ASE_DEFAULT_GIT_ROOT:-}"
  fi
  if [[ -n $git_root ]]; then
    scripts_dir="$git_root/scripts"
  fi

  mkdir -p "$(dirname "$cfg")"
  if [[ -n $scripts_dir ]]; then
    mkdir -p "$scripts_dir"
  fi
  {
    echo '# Generated by ase — edit as needed'
    if [[ -n $git_root ]]; then
      printf 'ASE_SCRIPTS_DIR=%q\n' "$scripts_dir"
      printf 'ASE_GIT_ROOT=%q\n' "$git_root"
      echo 'ASE_GIT_SCRIPTS_REL="script-hub"'
    else
      echo 'ASE_SCRIPTS_DIR="$HOME/.local/share/ase/scripts"'
      echo 'ASE_GIT_ROOT="$HOME/.local/share/ase"'
    fi
    echo 'ASE_GIT_REMOTE="origin"'
    echo 'ASE_GIT_BRANCH="main"'
    if [[ $(id -u) -eq 0 ]]; then
      printf 'ASE_BIN_USER=%q\n' "$ASE_SYSTEM_BIN"
    else
      echo 'ASE_BIN_USER="$HOME/bin"'
    fi
  } >"$cfg"
  echo "ase: wrote default config to $cfg" >&2
}

ase_warn_path_missing() {
  local bin_dir=$1
  [[ -n $bin_dir ]] || return 0
  case ":${PATH}:" in
    *":$bin_dir:"*) return 0 ;;
  esac
  echo "ase: $bin_dir is not on PATH; the command may not run until you add it or use -a." >&2
  echo "ase:  export PATH=\"$bin_dir:\$PATH\"" >&2
  echo "ase:  or: ase install <name> -a  # -> $ASE_SYSTEM_BIN" >&2
}

ase_load_config() {
  local cfg="${ASE_CONFIG:-$HOME/.config/ase/config}"
  if [[ ! -f $cfg ]]; then
    ase_write_default_config "$cfg"
  fi
  if [[ -f $cfg ]]; then
    # shellcheck disable=SC1090
    source "$cfg"
  fi

  if [[ -z ${ASE_SCRIPTS_DIR:-} ]]; then
    ase_die "ASE_SCRIPTS_DIR is not set (env or $cfg)"
  fi

  if [[ ! -d $ASE_SCRIPTS_DIR ]]; then
    mkdir -p "$ASE_SCRIPTS_DIR" || ase_die "cannot create scripts directory: $ASE_SCRIPTS_DIR"
  fi

  ASE_GIT_REMOTE="${ASE_GIT_REMOTE:-origin}"
  ASE_GIT_BRANCH="${ASE_GIT_BRANCH:-main}"
  ASE_BIN_USER="${ASE_BIN_USER:-$HOME/bin}"

  if [[ -z ${ASE_GIT_ROOT:-} ]]; then
    if ! command -v git >/dev/null 2>&1; then
      ase_die "git not found; set ASE_GIT_ROOT explicitly"
    fi
    ASE_GIT_ROOT=$(git -C "$ASE_SCRIPTS_DIR" rev-parse --show-toplevel 2>/dev/null) || \
      ase_die "ASE_SCRIPTS_DIR is not inside a git repo; set ASE_GIT_ROOT"
  fi

  ASE_SCRIPTS_DIR=$(ase_canonical_path "$ASE_SCRIPTS_DIR")
  ASE_GIT_ROOT=$(ase_canonical_path "$ASE_GIT_ROOT")

  local prefix="$ASE_GIT_ROOT/"
  if [[ -n ${ASE_GIT_SCRIPTS_REL:-} ]]; then
    if [[ $ASE_SCRIPTS_DIR == "$ASE_GIT_ROOT" || $ASE_SCRIPTS_DIR == "$prefix"* ]]; then
      if [[ $ASE_SCRIPTS_DIR == "$ASE_GIT_ROOT" ]]; then
        ASE_SCRIPTS_REL=""
      else
        ASE_SCRIPTS_REL="${ASE_SCRIPTS_DIR#"$prefix"}"
      fi
    else
      ASE_SCRIPTS_REL=""
    fi
  elif [[ $ASE_SCRIPTS_DIR != "$ASE_GIT_ROOT" && $ASE_SCRIPTS_DIR != "$prefix"* ]]; then
    ase_die "ASE_SCRIPTS_DIR must be inside ASE_GIT_ROOT (or set ASE_GIT_SCRIPTS_REL for an external scripts dir)"
  elif [[ $ASE_SCRIPTS_DIR == "$ASE_GIT_ROOT" ]]; then
    ASE_SCRIPTS_REL=""
  else
    ASE_SCRIPTS_REL="${ASE_SCRIPTS_DIR#"$prefix"}"
  fi
}

# Source config if present; do not create or validate scripts/git layout.
ase_try_source_config() {
  local cfg="${ASE_CONFIG:-$HOME/.config/ase/config}"
  [[ -f $cfg ]] || return 1
  # shellcheck disable=SC1090
  source "$cfg"
  ASE_BIN_USER="${ASE_BIN_USER:-$HOME/bin}"
  return 0
}

ase_read_install_names_from_file() {
  local list_file=$1
  [[ -f $list_file ]] || return 0
  grep -vE '^[[:space:]]*(#|$)' "$list_file" | sed 's/[[:space:]]*$//' | sed '/^$/d'
}

ase_require_scripts_dir() {
  ase_load_config
  if [[ ! -d $ASE_SCRIPTS_DIR ]]; then
    ase_die "scripts directory does not exist: $ASE_SCRIPTS_DIR"
  fi
}

# stdout: one script basename per line
ase_enumerate_scripts() {
  ase_require_scripts_dir
  find "$ASE_SCRIPTS_DIR" -maxdepth 1 -type f ! -name '.*' -printf '%f\n' 2>/dev/null | sort ||
    find "$ASE_SCRIPTS_DIR" -maxdepth 1 -type f ! -name '.*' -exec basename {} \; | sort
}

ase_resolve_script_path() {
  local name=$1
  ase_require_scripts_dir
  if [[ -z $name || $name == *"/"* || $name == *".."* ]]; then
    ase_die "invalid script name: ${name:-<empty>}"
  fi
  local path="$ASE_SCRIPTS_DIR/$name"
  if [[ ! -f $path ]]; then
    echo "ase: script not found: $name" >&2
    return 2
  fi
  echo "$path"
}

ase_maybe_chmod_executable() {
  local file=$1
  [[ -f $file ]] || return 0
  if head -n1 "$file" 2>/dev/null | grep -qE '^#!'; then
    chmod +x "$file" 2>/dev/null || true
  fi
}

ase_script_description_line() {
  local file=$1
  local first
  first=$(head -n1 "$file" 2>/dev/null || true)
  if [[ $first == '#!'* ]]; then
    head -n2 "$file" | tail -n1
  else
    printf '%s\n' "$first"
  fi
}

ase_script_first_line_is_shebang() {
  head -n1 "$1" 2>/dev/null | grep -qE '^#!'
}

ase_install_bin_entry() {
  local bindir=$1 name=$2 canon=$3
  local dest="$bindir/$name"

  if ase_script_first_line_is_shebang "$canon"; then
    ase_maybe_chmod_executable "$canon"
    ln -sf "$canon" "$dest"
  else
    {
      echo '#!/usr/bin/env bash'
      printf 'exec bash %q "$@"\n' "$canon"
    } >"$dest"
    chmod +x "$dest"
  fi
}

ase_remove_bin_entry_if_matches() {
  local entry=$1 canon=$2 script_path=$3
  [[ -e $entry || -L $entry ]] || return 1

  if [[ -L $entry ]]; then
    local dest
    dest=$(readlink "$entry" 2>/dev/null || true)
    if [[ "$dest" == "$canon" || "$dest" == "$script_path" ]]; then
      rm -f "$entry"
      return 0
    fi
    if [[ -n $canon ]]; then
      ase_unlink_if_points_to "$entry" "$canon" && return 0
    fi
    return 1
  fi

  if [[ -f $entry ]] && ase_script_first_line_is_shebang "$entry"; then
    local entry_canon
    entry_canon=$(ase_canonical_path "$entry" 2>/dev/null) || true
    if [[ -n $entry_canon && ( $entry_canon == "$canon" || $entry_canon == "$script_path" ) ]]; then
      rm -f "$entry"
      return 0
    fi
  fi

  if [[ -f $entry ]] && head -n1 "$entry" 2>/dev/null | grep -qE '^#!/usr/bin/env bash$'; then
    if grep -Fq "$(printf 'exec bash %q' "$canon")" "$entry" 2>/dev/null; then
      rm -f "$entry"
      return 0
    fi
  fi
  return 1
}

ase_git_remote_ref() {
  echo "${ASE_GIT_REMOTE}/${ASE_GIT_BRANCH}"
}

ase_script_hub_list_path() {
  ase_load_config
  echo "$ASE_GIT_ROOT/$ASE_SCRIPT_HUB_LIST_REL"
}

ase_install_list_path() {
  ase_load_config
  echo "$ASE_GIT_ROOT/$ASE_INSTALL_LIST_REL"
}

ase_read_script_hub_names() {
  local list_file
  list_file=$(ase_script_hub_list_path)
  [[ -f $list_file ]] || return 1
  grep -vE '^[[:space:]]*(#|$)' "$list_file" | sed 's/[[:space:]]*$//' | sed '/^$/d' |
    awk -F'\t' 'NF >= 2 { print $2; next } { print }'
}

ase_install_list_add() {
  local name=$1
  local list_file names=()
  list_file=$(ase_install_list_path)
  mkdir -p "$(dirname "$list_file")"
  if [[ -f $list_file ]]; then
    while IFS= read -r line; do
      [[ -n $line ]] || continue
      [[ $line == "$name" ]] && return 0
      names+=("$line")
    done < <(grep -vE '^[[:space:]]*(#|$)' "$list_file" | sed 's/[[:space:]]*$//' | sed '/^$/d' || true)
  fi
  names+=("$name")
  printf '%s\n' "${names[@]}" | sort -u >"$list_file"
}

ase_install_list_remove() {
  local name=$1
  local list_file
  list_file=$(ase_install_list_path)
  [[ -f $list_file ]] || return 0
  local tmp
  tmp=$(mktemp)
  grep -vE '^[[:space:]]*(#|$)' "$list_file" | sed 's/[[:space:]]*$//' | sed '/^$/d' | grep -Fxv "$name" >"$tmp" || true
  mv "$tmp" "$list_file"
}

ase_read_install_names() {
  local list_file
  list_file=$(ase_install_list_path)
  [[ -f $list_file ]] || return 0
  grep -vE '^[[:space:]]*(#|$)' "$list_file" | sed 's/[[:space:]]*$//' | sed '/^$/d'
}

ase_can_prompt() {
  [[ -t 0 ]] && return 0
  [[ -r /dev/tty && -w /dev/tty ]]
}

ase_prompt_yn() {
  local question=$1
  local default=${2:-n}
  local hint answer
  if [[ $default == y ]]; then
    hint="[Y/n]"
  else
    hint="[y/N]"
  fi
  while true; do
    if [[ -t 0 ]]; then
      read -r -p "$question $hint " answer || true
    elif [[ -r /dev/tty ]]; then
      read -r -p "$question $hint " answer </dev/tty || true
    else
      return 1
    fi
    answer=${answer:-$default}
    case ${answer,,} in
      y | yes) return 0 ;;
      n | no) return 1 ;;
      *) echo "ase: 请输入 y 或 n。" >&2 ;;
    esac
  done
}

ase_hub_script_git_path() {
  local basename=$1
  local rel="${ASE_GIT_SCRIPTS_REL:-script-hub}"
  if [[ -n $rel ]]; then
    echo "${rel}/${basename}"
  else
    echo "$basename"
  fi
}

ase_fuzzy_match_names() {
  local query=$1
  shift
  local name qlower nlower
  qlower=${query,,}
  [[ -n $qlower ]] || return 0
  for name; do
    nlower=${name,,}
    if [[ $nlower == *"$qlower"* ]]; then
      printf '%s\n' "$name"
    fi
  done
}

ase_git_path_in_repo() {
  local basename=$1
  local rel="${ASE_GIT_SCRIPTS_REL:-$ASE_SCRIPTS_REL}"
  if [[ -n $rel ]]; then
    echo "${rel}/${basename}"
  else
    echo "$basename"
  fi
}

ase_unlink_if_points_to() {
  local link_path=$1
  local target=$2
  [[ -e $link_path || -L $link_path ]] || return 0
  [[ -L $link_path ]] || return 0
  local dest
  dest=$(readlink "$link_path" 2>/dev/null) || return 0
  if [[ "$dest" == "$target" ]]; then
    rm -f "$link_path"
    return 0
  fi
  local abs_dest
  if [[ $dest == /* ]]; then
    abs_dest=$(ase_canonical_path "$dest" 2>/dev/null) || abs_dest=$dest
  else
    abs_dest=$(ase_canonical_path "$(dirname "$link_path")/$dest" 2>/dev/null) || return 0
  fi
  if [[ $abs_dest == "$target" ]]; then
    rm -f "$link_path"
  fi
}

ase_run_privileged() {
  if [[ $(id -u) -eq 0 ]]; then
    "$@"
  elif command -v sudo >/dev/null 2>&1; then
    sudo "$@"
  else
    ase_die "need root or sudo for: $*"
  fi
}

ase_path_is_under() {
  local path=$1
  local root=$2
  [[ -n $path && -n $root ]] || return 1
  [[ $path == "$root" || $path == "$root"/* ]]
}

ase_resolve_executable_path() {
  local cmd=$1
  local path link_dir
  [[ -n $cmd ]] || return 1
  if [[ $cmd == /* ]]; then
    path=$cmd
  else
    path=$(command -v "$cmd" 2>/dev/null) || return 1
  fi
  while [[ -L $path ]]; do
    link_dir=$(cd "$(dirname "$path")" && pwd)
    path=$(readlink "$path")
    [[ $path == /* ]] || path="$link_dir/$path"
  done
  if [[ -f $path ]]; then
    printf '%s/%s\n' "$(cd "$(dirname "$path")" && pwd -P)" "$(basename "$path")"
    return 0
  fi
  return 1
}

ase_share_looks_installed() {
  local dir=$1
  [[ -f $dir/ase && -f $dir/lib/ase-common.sh ]]
}

ase_is_default_share_path() {
  local d=$1
  [[ $d == /usr/local/share/ase ]] && return 0
  [[ $d == "$HOME/.local/share/ase" ]] && return 0
  return 1
}

ase_should_remove_share_dir() {
  local d=$1
  local share_from_cmd=$2
  ase_is_default_share_path "$d" && return 0
  [[ -n $share_from_cmd && $d == "$share_from_cmd" ]] && return 0
  if [[ -n ${ASE_GIT_ROOT:-} ]]; then
    local git_root
    git_root=$(ase_canonical_path "$ASE_GIT_ROOT" 2>/dev/null) || git_root=$ASE_GIT_ROOT
    [[ $d == "$git_root" ]] && return 0
  fi
  return 1
}

ase_detect_share_from_command() {
  local exe share
  exe=$(ase_resolve_executable_path ase 2>/dev/null) || return 1
  share=$(cd "$(dirname "$exe")" && pwd -P)
  ase_share_looks_installed "$share" || return 1
  printf '%s\n' "$share"
}

ase_bashrc_completion_begin='# >>> ase completion >>>'
ase_bashrc_completion_end='# <<< ase completion <<<'
ase_bashrc_path_begin='# >>> ase path >>>'
ase_bashrc_path_end='# <<< ase path <<<'

ase_remove_bashrc_block() {
  local begin=$1
  local end=$2
  local label=$3
  local bashrc="${HOME}/.bashrc"
  local tmp in_block=0 changed=0

  [[ -f $bashrc ]] || return 0
  grep -qF "$begin" "$bashrc" 2>/dev/null || return 0

  tmp=$(mktemp)
  while IFS= read -r line || [[ -n $line ]]; do
    if [[ $line == "$begin" ]]; then
      in_block=1
      changed=1
      continue
    fi
    if (( in_block )); then
      [[ $line == "$end" ]] && in_block=0
      continue
    fi
    printf '%s\n' "$line"
  done < "$bashrc" > "$tmp"
  if (( changed )); then
    mv "$tmp" "$bashrc"
    echo "ase uninstallme: removed $label block from $bashrc" >&2
  else
    rm -f "$tmp"
  fi
}

ase_remove_bashrc_completion_block() {
  ase_remove_bashrc_block "$ase_bashrc_completion_begin" "$ase_bashrc_completion_end" "completion"
}

ase_remove_bashrc_path_block() {
  ase_remove_bashrc_block "$ase_bashrc_path_begin" "$ase_bashrc_path_end" "path"
}

ase_remove_system_completion_hooks() {
  local profile_d="/etc/profile.d/ase-completion.sh"
  local bash_comp_d="/etc/bash_completion.d/ase"
  local removed=0

  if [[ -f $profile_d || -L $profile_d ]]; then
    ase_run_privileged rm -f "$profile_d"
    echo "ase uninstallme: removed $profile_d" >&2
    removed=1
  fi
  if [[ -f $bash_comp_d || -L $bash_comp_d ]]; then
    ase_run_privileged rm -f "$bash_comp_d"
    echo "ase uninstallme: removed $bash_comp_d" >&2
    removed=1
  fi
  (( removed )) || true
}

ase_remove_ase_bin_symlink() {
  local link=$1
  local share=$2
  [[ -e $link || -L $link ]] || return 1
  [[ -L $link ]] || return 1
  local dest abs_dest share_ase
  share_ase="$share/ase"
  dest=$(readlink "$link" 2>/dev/null) || return 1
  if [[ $dest == "$share_ase" ]]; then
    rm -f "$link"
    return 0
  fi
  if [[ $dest == /* ]]; then
    abs_dest=$(ase_canonical_path "$dest" 2>/dev/null) || abs_dest=$dest
  else
    abs_dest=$(ase_canonical_path "$(dirname "$link")/$dest" 2>/dev/null) || return 1
  fi
  if [[ $abs_dest == "$share_ase" ]] || ase_path_is_under "$(dirname "$abs_dest")" "$share"; then
    rm -f "$link"
    return 0
  fi
  return 1
}

ase_remove_script_bin_links() {
  local name=$1
  local script_path=$2
  local canon="" bindir link_path

  ASE_BIN_USER="${ASE_BIN_USER:-$HOME/bin}"
  if [[ -f $script_path ]]; then
    canon=$(ase_canonical_path "$script_path" 2>/dev/null) || canon=""
  fi
  for bindir in "$ASE_BIN_USER" "$ASE_SYSTEM_BIN" /usr/bin; do
    link_path="$bindir/$name"
    if ase_remove_bin_entry_if_matches "$link_path" "$canon" "$script_path"; then
      echo "ase uninstallme: removed $link_path" >&2
    fi
  done
  ase_forget_cmd_hash "$name"
}

ase_deferred_rm_paths() {
  local -a paths=("$@")
  local script
  [[ ${#paths[@]} -gt 0 ]] || return 0
  script=$(mktemp)
  {
    echo '#!/usr/bin/env bash'
    echo 'sleep 1'
    for p in "${paths[@]}"; do
      printf 'rm -rf %q\n' "$p"
    done
    printf 'rm -rf %q\n' "$script"
  } >"$script"
  chmod +x "$script"
  nohup "$script" >/dev/null 2>&1 &
}
