# Shared helpers for ase (sourced, not executed directly)
# shellcheck shell=bash

ASE_SYSTEM_BIN="/usr/local/bin"
ASE_SCRIPT_HUB_LIST_REL="data/script-hub.list"
ASE_INSTALL_LIST_REL="data/install.list"

ase_die() {
  echo "ase: $*" >&2
  exit 1
}

# Drop bash's cached path for a command name (no-op outside bash).
ase_forget_cmd_hash() {
  local name=$1
  [[ -n $name && -n ${BASH_VERSION:-} ]] || return 0
  hash -d "$name" 2>/dev/null || true
}

ase_canonical_path() {
  local path=$1
  if [[ -z $path ]]; then
    return 1
  fi
  if [[ -d $path ]]; then
    (cd "$path" && pwd -P)
  elif [[ -f $path ]]; then
    local dir
    dir=$(cd "$(dirname "$path")" && pwd -P)
    echo "$dir/$(basename "$path")"
  else
    if command -v readlink >/dev/null 2>&1; then
      readlink -f "$path" 2>/dev/null && return 0
    fi
    ase_die "path not found: $path"
  fi
}

ase_write_default_config() {
  local cfg=$1
  local git_root="${ASE_DEFAULT_GIT_ROOT:-}"
  local scripts_dir=""
  if [[ -n $git_root ]] && command -v git >/dev/null 2>&1; then
    git_root=$(git -C "$git_root" rev-parse --show-toplevel 2>/dev/null) || git_root="${ASE_DEFAULT_GIT_ROOT:-}"
  fi
  if [[ -n $git_root ]]; then
    scripts_dir="$HOME/scripts"
  fi

  mkdir -p "$(dirname "$cfg")"
  {
    echo '# Generated by ase — edit as needed'
    if [[ -n $git_root ]]; then
      printf 'ASE_SCRIPTS_DIR=%q\n' "$scripts_dir"
      printf 'ASE_GIT_ROOT=%q\n' "$git_root"
      echo 'ASE_GIT_SCRIPTS_REL="script-hub"'
    else
      echo 'ASE_SCRIPTS_DIR="$HOME/scripts"'
    fi
    echo 'ASE_GIT_REMOTE="origin"'
    echo 'ASE_GIT_BRANCH="main"'
    if [[ $(id -u) -eq 0 ]]; then
      printf 'ASE_BIN_USER=%q\n' "$ASE_SYSTEM_BIN"
    else
      echo 'ASE_BIN_USER="$HOME/bin"'
    fi
  } >"$cfg"
  echo "ase: wrote default config to $cfg" >&2
}

ase_warn_path_missing() {
  local bin_dir=$1
  [[ -n $bin_dir ]] || return 0
  case ":${PATH}:" in
    *":$bin_dir:"*) return 0 ;;
  esac
  echo "ase: $bin_dir is not on PATH; the command may not run until you add it or use -a." >&2
  echo "ase:  export PATH=\"$bin_dir:\$PATH\"" >&2
  echo "ase:  or: ase install <name> -a  # -> $ASE_SYSTEM_BIN" >&2
}

ase_load_config() {
  local cfg="${ASE_CONFIG:-$HOME/.config/ase/config}"
  if [[ ! -f $cfg ]]; then
    ase_write_default_config "$cfg"
  fi
  if [[ -f $cfg ]]; then
    # shellcheck disable=SC1090
    source "$cfg"
  fi

  if [[ -z ${ASE_SCRIPTS_DIR:-} ]]; then
    ase_die "ASE_SCRIPTS_DIR is not set (env or $cfg)"
  fi

  ASE_GIT_REMOTE="${ASE_GIT_REMOTE:-origin}"
  ASE_GIT_BRANCH="${ASE_GIT_BRANCH:-main}"
  ASE_BIN_USER="${ASE_BIN_USER:-$HOME/bin}"

  if [[ -z ${ASE_GIT_ROOT:-} ]]; then
    if ! command -v git >/dev/null 2>&1; then
      ase_die "git not found; set ASE_GIT_ROOT explicitly"
    fi
    ASE_GIT_ROOT=$(git -C "$ASE_SCRIPTS_DIR" rev-parse --show-toplevel 2>/dev/null) || \
      ase_die "ASE_SCRIPTS_DIR is not inside a git repo; set ASE_GIT_ROOT"
  fi

  ASE_SCRIPTS_DIR=$(ase_canonical_path "$ASE_SCRIPTS_DIR")
  ASE_GIT_ROOT=$(ase_canonical_path "$ASE_GIT_ROOT")

  local prefix="$ASE_GIT_ROOT/"
  if [[ -n ${ASE_GIT_SCRIPTS_REL:-} ]]; then
    if [[ $ASE_SCRIPTS_DIR == "$ASE_GIT_ROOT" || $ASE_SCRIPTS_DIR == "$prefix"* ]]; then
      if [[ $ASE_SCRIPTS_DIR == "$ASE_GIT_ROOT" ]]; then
        ASE_SCRIPTS_REL=""
      else
        ASE_SCRIPTS_REL="${ASE_SCRIPTS_DIR#"$prefix"}"
      fi
    else
      ASE_SCRIPTS_REL=""
    fi
  elif [[ $ASE_SCRIPTS_DIR != "$ASE_GIT_ROOT" && $ASE_SCRIPTS_DIR != "$prefix"* ]]; then
    ase_die "ASE_SCRIPTS_DIR must be inside ASE_GIT_ROOT (or set ASE_GIT_SCRIPTS_REL for an external scripts dir)"
  elif [[ $ASE_SCRIPTS_DIR == "$ASE_GIT_ROOT" ]]; then
    ASE_SCRIPTS_REL=""
  else
    ASE_SCRIPTS_REL="${ASE_SCRIPTS_DIR#"$prefix"}"
  fi
}

ase_require_scripts_dir() {
  ase_load_config
  if [[ ! -d $ASE_SCRIPTS_DIR ]]; then
    ase_die "scripts directory does not exist: $ASE_SCRIPTS_DIR"
  fi
}

# stdout: one script basename per line
ase_enumerate_scripts() {
  ase_require_scripts_dir
  find "$ASE_SCRIPTS_DIR" -maxdepth 1 -type f ! -name '.*' -printf '%f\n' 2>/dev/null | sort ||
    find "$ASE_SCRIPTS_DIR" -maxdepth 1 -type f ! -name '.*' -exec basename {} \; | sort
}

ase_resolve_script_path() {
  local name=$1
  ase_require_scripts_dir
  if [[ -z $name || $name == *"/"* || $name == *".."* ]]; then
    ase_die "invalid script name: ${name:-<empty>}"
  fi
  local path="$ASE_SCRIPTS_DIR/$name"
  if [[ ! -f $path ]]; then
    echo "ase: script not found: $name" >&2
    return 2
  fi
  echo "$path"
}

ase_maybe_chmod_executable() {
  local file=$1
  [[ -f $file ]] || return 0
  if head -n1 "$file" 2>/dev/null | grep -qE '^#!'; then
    chmod +x "$file" 2>/dev/null || true
  fi
}

ase_script_description_line() {
  local file=$1
  local first
  first=$(head -n1 "$file" 2>/dev/null || true)
  if [[ $first == '#!'* ]]; then
    head -n2 "$file" | tail -n1
  else
    printf '%s\n' "$first"
  fi
}

ase_script_first_line_is_shebang() {
  head -n1 "$1" 2>/dev/null | grep -qE '^#!'
}

ase_install_bin_entry() {
  local bindir=$1 name=$2 canon=$3
  local dest="$bindir/$name"

  if ase_script_first_line_is_shebang "$canon"; then
    ase_maybe_chmod_executable "$canon"
    ln -sf "$canon" "$dest"
  else
    {
      echo '#!/usr/bin/env bash'
      printf 'exec bash %q "$@"\n' "$canon"
    } >"$dest"
    chmod +x "$dest"
  fi
}

ase_remove_bin_entry_if_matches() {
  local entry=$1 canon=$2 script_path=$3
  [[ -e $entry || -L $entry ]] || return 1

  if [[ -L $entry ]]; then
    local dest
    dest=$(readlink "$entry" 2>/dev/null || true)
    if [[ "$dest" == "$canon" || "$dest" == "$script_path" ]]; then
      rm -f "$entry"
      return 0
    fi
    if [[ -n $canon ]]; then
      ase_unlink_if_points_to "$entry" "$canon" && return 0
    fi
    return 1
  fi

  if [[ -f $entry ]] && ase_script_first_line_is_shebang "$entry"; then
    local entry_canon
    entry_canon=$(ase_canonical_path "$entry" 2>/dev/null) || true
    if [[ -n $entry_canon && ( $entry_canon == "$canon" || $entry_canon == "$script_path" ) ]]; then
      rm -f "$entry"
      return 0
    fi
  fi

  if [[ -f $entry ]] && head -n1 "$entry" 2>/dev/null | grep -qE '^#!/usr/bin/env bash$'; then
    if grep -Fq "$(printf 'exec bash %q' "$canon")" "$entry" 2>/dev/null; then
      rm -f "$entry"
      return 0
    fi
  fi
  return 1
}

ase_git_remote_ref() {
  echo "${ASE_GIT_REMOTE}/${ASE_GIT_BRANCH}"
}

ase_script_hub_list_path() {
  ase_load_config
  echo "$ASE_GIT_ROOT/$ASE_SCRIPT_HUB_LIST_REL"
}

ase_install_list_path() {
  ase_load_config
  echo "$ASE_GIT_ROOT/$ASE_INSTALL_LIST_REL"
}

ase_read_script_hub_names() {
  local list_file
  list_file=$(ase_script_hub_list_path)
  [[ -f $list_file ]] || return 1
  grep -vE '^[[:space:]]*(#|$)' "$list_file" | sed 's/[[:space:]]*$//' | sed '/^$/d'
}

ase_install_list_add() {
  local name=$1
  local list_file names=()
  list_file=$(ase_install_list_path)
  mkdir -p "$(dirname "$list_file")"
  if [[ -f $list_file ]]; then
    while IFS= read -r line; do
      [[ -n $line ]] || continue
      [[ $line == "$name" ]] && return 0
      names+=("$line")
    done < <(grep -vE '^[[:space:]]*(#|$)' "$list_file" | sed 's/[[:space:]]*$//' | sed '/^$/d' || true)
  fi
  names+=("$name")
  printf '%s\n' "${names[@]}" | sort -u >"$list_file"
}

ase_install_list_remove() {
  local name=$1
  local list_file
  list_file=$(ase_install_list_path)
  [[ -f $list_file ]] || return 0
  local tmp
  tmp=$(mktemp)
  grep -vE '^[[:space:]]*(#|$)' "$list_file" | sed 's/[[:space:]]*$//' | sed '/^$/d' | grep -Fxv "$name" >"$tmp" || true
  mv "$tmp" "$list_file"
}

ase_read_install_names() {
  local list_file
  list_file=$(ase_install_list_path)
  [[ -f $list_file ]] || return 0
  grep -vE '^[[:space:]]*(#|$)' "$list_file" | sed 's/[[:space:]]*$//' | sed '/^$/d'
}

ase_can_prompt() {
  [[ -t 0 ]] && return 0
  [[ -r /dev/tty && -w /dev/tty ]]
}

ase_prompt_yn() {
  local question=$1
  local default=${2:-n}
  local hint answer
  if [[ $default == y ]]; then
    hint="[Y/n]"
  else
    hint="[y/N]"
  fi
  while true; do
    if [[ -t 0 ]]; then
      read -r -p "$question $hint " answer || true
    elif [[ -r /dev/tty ]]; then
      read -r -p "$question $hint " answer </dev/tty || true
    else
      return 1
    fi
    answer=${answer:-$default}
    case ${answer,,} in
      y | yes) return 0 ;;
      n | no) return 1 ;;
      *) echo "ase: 请输入 y 或 n。" >&2 ;;
    esac
  done
}

ase_hub_script_git_path() {
  local basename=$1
  local rel="${ASE_GIT_SCRIPTS_REL:-script-hub}"
  if [[ -n $rel ]]; then
    echo "${rel}/${basename}"
  else
    echo "$basename"
  fi
}

ase_fuzzy_match_names() {
  local query=$1
  shift
  local name qlower nlower
  qlower=${query,,}
  [[ -n $qlower ]] || return 0
  for name; do
    nlower=${name,,}
    if [[ $nlower == *"$qlower"* ]]; then
      printf '%s\n' "$name"
    fi
  done
}

ase_git_path_in_repo() {
  local basename=$1
  local rel="${ASE_GIT_SCRIPTS_REL:-$ASE_SCRIPTS_REL}"
  if [[ -n $rel ]]; then
    echo "${rel}/${basename}"
  else
    echo "$basename"
  fi
}

ase_unlink_if_points_to() {
  local link_path=$1
  local target=$2
  [[ -e $link_path || -L $link_path ]] || return 0
  [[ -L $link_path ]] || return 0
  local dest
  dest=$(readlink "$link_path" 2>/dev/null) || return 0
  if [[ "$dest" == "$target" ]]; then
    rm -f "$link_path"
    return 0
  fi
  local abs_dest
  if [[ $dest == /* ]]; then
    abs_dest=$(ase_canonical_path "$dest" 2>/dev/null) || abs_dest=$dest
  else
    abs_dest=$(ase_canonical_path "$(dirname "$link_path")/$dest" 2>/dev/null) || return 0
  fi
  if [[ $abs_dest == "$target" ]]; then
    rm -f "$link_path"
  fi
}
